name: comp-db
services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: comp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
########################################################
# # How to run the database
########################################################

# # Start the database
# docker-compose up -d

# # If the above command doesn't work, use this instead:
# docker compose up -d

# # Run migrations
# bunx prisma migrate dev
